from mininet.topo import Topo

class MyTopo( Topo ):
    "Simple topology example."

    def __init__( self ):
        "Create custom topo."

        # Initialize topology
        Topo.__init__( self )
        Zurich = self.addSwitch('Zurich0')
        Geneva = self.addSwitch('Geneva0')
        Budapest = self.addSwitch('Budapest0')
        Stuttgart = self.addSwitch('Stuttgart0')
        Madrid = self.addSwitch('Madrid0')
        Lisbon = self.addSwitch('Lisbon0')
        Milan = self.addSwitch('Milan0')
        Barcelona = self.addSwitch('Barcelona0')
        Paris = self.addSwitch('Paris0')
        London = self.addSwitch('London0')
        Tokyo = self.addSwitch('Tokyo0')
        Chicago = self.addSwitch('Chicago0')
        Washington = self.addSwitch('Washingto0')
        Miami = self.addSwitch('Miami0')
        LosAngeles = self.addSwitch('LosAngele0')
        PaloAlto = self.addSwitch('PaloAlto0')
        SanJose = self.addSwitch('SanJose0')
        HongKong = self.addSwitch('HongKong0')
        Singapore = self.addSwitch('Singapore0')
        Toronto = self.addSwitch('Toronto0')
        NewYork = self.addSwitch('NewYork0')
        Frankfurt = self.addSwitch('Frankfurt0')
        Cologne = self.addSwitch('Cologne0')
        Hanover = self.addSwitch('Hanover0')
        Amsterdam = self.addSwitch('Amsterdam0')
        Ashburn = self.addSwitch('Ashburn0')
        Hamburg = self.addSwitch('Hamburg0')
        Dortmund = self.addSwitch('Dortmund0')
        Dusseldorf = self.addSwitch('Dusseldor0')
        Vienna = self.addSwitch('Vienna0')
        Munich = self.addSwitch('Munich0')
        Copenhagen = self.addSwitch('Copenhage0')
        Stockholm = self.addSwitch('Stockholm0')
        Warsaw = self.addSwitch('Warsaw0')
        Moscow = self.addSwitch('Moscow0')
        Berlin = self.addSwitch('Berlin0')
        Leipzig = self.addSwitch('Leipzig0')
        Prague = self.addSwitch('Prague0')
        Nuremberg = self.addSwitch('Nuremberg0')

        hostCarlos = self.addHost('carlos0')
        hostJonas = self.addHost('jonas0')
	hostLond = self.addHost('hLondo0')
        # Add links
        self.addLink(Zurich, Paris)
        self.addLink(Zurich, Geneva)
        self.addLink(Zurich, Stuttgart)
        self.addLink(Zurich, Milan)
        self.addLink(Zurich, Barcelona)
        self.addLink(Geneva, Paris)
        self.addLink(Geneva, Milan)
        self.addLink(Budapest, Vienna)
        self.addLink(Budapest, Munich)
        self.addLink(Madrid, Paris)
        self.addLink(Madrid, Lisbon)
        self.addLink(Madrid, Barcelona)
        self.addLink(Milan, Paris)
        self.addLink(Paris, London)
        self.addLink(Paris, Frankfurt)
        self.addLink(Paris, Amsterdam)
        self.addLink(Paris, Ashburn)
        self.addLink(London, NewYork)
        self.addLink(London, Frankfurt)
        self.addLink(London, Amsterdam)
        self.addLink(London, Ashburn)
        self.addLink(London, Dusseldorf)
        self.addLink(Tokyo, SanJose)
        self.addLink(Tokyo, HongKong)
        self.addLink(Chicago, Toronto)
        self.addLink(Chicago, NewYork)
        self.addLink(Chicago, PaloAlto)
        self.addLink(Washington, Ashburn)
        self.addLink(Washington, NewYork)
        self.addLink(Washington, Miami)
        self.addLink(Washington, LosAngeles)
        self.addLink(LosAngeles, SanJose)
        self.addLink(LosAngeles, HongKong)
        self.addLink(LosAngeles, Singapore)
        self.addLink(LosAngeles, PaloAlto)
        self.addLink(PaloAlto, SanJose)
        self.addLink(PaloAlto, Ashburn)
        self.addLink(PaloAlto, NewYork)
        self.addLink(SanJose, NewYork)
        self.addLink(HongKong, Singapore)
        self.addLink(Singapore, Frankfurt)
        self.addLink(Toronto, NewYork)
        self.addLink(NewYork, Leipzig)
        self.addLink(NewYork, Frankfurt)
        self.addLink(NewYork, Hanover)
        self.addLink(NewYork, Dusseldorf)
        self.addLink(Frankfurt, Moscow)
        self.addLink(Frankfurt, Amsterdam)
        self.addLink(Frankfurt, Ashburn)
        self.addLink(Hanover, Ashburn)
        self.addLink(Amsterdam, Hamburg)
        self.addLink(Amsterdam, Dusseldorf)
        self.addLink(Ashburn, Leipzig)
        self.addLink(Ashburn, Dusseldorf)
        self.addLink(Hamburg, Stockholm)
        self.addLink(Hamburg, Copenhagen)
        self.addLink(Vienna, Prague)
        self.addLink(Vienna, Munich)
        self.addLink(Copenhagen, Stockholm)
        self.addLink(Warsaw, Berlin)
        self.addLink(Warsaw, Nuremberg)
        self.addLink(Prague, Nuremberg)
	
	self.addLink(hostLond, Madrid)
        self.addLink(hostCarlos, Madrid)
        self.addLink(hostJonas, NewYork)
topos = { 'mytopo': ( lambda: MyTopo() ) }
